// <auto-generated />
namespace Store.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class added_shopping_cart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_shopping_cart));
        
        string IMigrationMetadata.Id
        {
            get { return "201901240627241_added_shopping_cart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
